#default by: 'id'
read_only_page:
    url: 'account/'
    admin_link: 'Admin'
    dashboard_link: 'Dashboard'
    campaigns_link: 'Campaigns'
    reports_link: 'Reports'
    creatives_link: 'Creatives'
    audiences_link: 'Audiences'
    activities_link: 'Activities'
    inventory_link: 'Inventory'    
    new_system_message_link: 'New Message'
    agency_group_link: 'Agency Groups'
    agencies_link: 'Agencies'
    advertiser_link: 'Advertisers'
    buisiness_inrelligence_reports: 'Business intelligence reports'
    customer_intelligence_dataset: 'Customer intelligence dataset'
    product_feature: 'Product features'
    login_screen_slides: 'Login screen slides'
    ad_server_tag_versions: 'Ad server tag versions'
    edit_my_account: 'Edit My Account'
    subscription: 'Subscriptions'
    report_inbox: 'Report Inbox'
    user_link: 'Users'
    create_new_user: 'Create New User'